ca: Fix panic when issuer_fingerprint is None
Some imported keys (like mine) have signatures that lack issuer
fingerprint. This causes the following panic:

    thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/ca.rs:549:22

This patch changes the comparison to compare Option types directly
without unwrapping the (potentially missing) issuer_fingerprint.